// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankSys.Models;

[Index("AccountNumber", Name = "UQ__Accounts__BE2ACD6F441E72AA", IsUnique = true)]
public partial class Account
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    public string AccountNumber { get; set; }

    public int CustomerId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Balance { get; set; }

    [Required]
    [StringLength(50)]
    public string AccountType { get; set; }

    public bool? IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    public bool IsFrozen { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Accounts")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Account")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    [InverseProperty("FromAccount")]
    public virtual ICollection<Transfer> TransferFromAccounts { get; set; } = new List<Transfer>();

    [InverseProperty("ToAccount")]
    public virtual ICollection<Transfer> TransferToAccounts { get; set; } = new List<Transfer>();
}