// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankSys.Models;

public partial class LoanPayment
{
    [Key]
    public int Id { get; set; }

    public int LoanId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PaidAt { get; set; }

    [ForeignKey("LoanId")]
    [InverseProperty("LoanPayments")]
    public virtual Loan Loan { get; set; }
}