// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankSys.Models;

public partial class Product
{
    [Key]
    public int Id { get; set; }

    public int ExternalId { get; set; }

    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    [StringLength(150)]
    public string Brand { get; set; }

    public DateTime CreatedAt { get; set; }
}