// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankSys.Models;

public partial class Transfer
{
    [Key]
    public int Id { get; set; }

    public int FromAccountId { get; set; }

    public int ToAccountId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("FromAccountId")]
    [InverseProperty("TransferFromAccounts")]
    public virtual Account FromAccount { get; set; }

    [ForeignKey("ToAccountId")]
    [InverseProperty("TransferToAccounts")]
    public virtual Account ToAccount { get; set; }
}