// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LoanSys.Models;

public partial class ApiLog
{
    [Key]
    public int Id { get; set; }

    [StringLength(10)]
    public string Method { get; set; }

    [StringLength(500)]
    public string Path { get; set; }

    public int? StatusCode { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RequestTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ResponseTime { get; set; }

    public int? DurationMs { get; set; }

    [Column("IPAddress")]
    [StringLength(50)]
    public string Ipaddress { get; set; }

    [StringLength(100)]
    public string UserName { get; set; }

    public string RequestBody { get; set; }

    public string ResponseBody { get; set; }

    [StringLength(1000)]
    public string QueryString { get; set; }

    [StringLength(200)]
    public string ControllerName { get; set; }

    [StringLength(200)]
    public string ActionName { get; set; }

    [StringLength(1000)]
    public string UserAgent { get; set; }

    public int? ResponseSize { get; set; }

    public bool? IsSuccess { get; set; }

    public string ExceptionMessage { get; set; }

    public string StackTrace { get; set; }
}