// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LoanSys.Models;

[Index("Email", Name = "UQ__Customer__A9D105342070D327", IsUnique = true)]
[Index("NationalId", Name = "UQ__Customer__E9AA32FA39276D41", IsUnique = true)]
public partial class Customer
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string FullName { get; set; }

    [Required]
    [StringLength(20)]
    public string NationalId { get; set; }

    [StringLength(200)]
    public string Email { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? MonthlyIncome { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Loan> Loans { get; set; } = new List<Loan>();
}