// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LoanSys.Models;

public partial class Loan
{
    [Key]
    public int Id { get; set; }

    public int CustomerId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal InterestRate { get; set; }

    public int TermMonths { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Loans")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Loan")]
    public virtual ICollection<LoanInstallment> LoanInstallments { get; set; } = new List<LoanInstallment>();

    [InverseProperty("Loan")]
    public virtual ICollection<LoanPayment> LoanPayments { get; set; } = new List<LoanPayment>();
}